### ISSUE TITLE
Marvin Nichols still displaying in 2020

### ISSUE THREAD

**Issue by SabrinaAnderson** [TNRIS/iswp2017#205]
In an email you had said that you changed the functionality so that sources would no longer display in the map if DisplayZero = 'y', but I am still seeing Marvin Nichols displaying when the 2020 decade is selected and it shouldn't show up 2070.

**Comment by adambreznicky** [comment]
sorry, i wasn't clear, that was my fault. 
i had fixed that issue already but in my development environment alongside the other work i was doing. i hadn't pushed those changes up to the staging environment yet because of our previous agreement not to push new changes while a review was currently underway.

this change, among others, have been implemented and pushed into staging for your review.

**Comment by SabrinaAnderson** [comment]
That makes sense. No worries. Please send me a message when you have the new entity zero display functionality pushed to staging and I'll run a final test on it.
