### ISSUE TITLE
project triangles mapping in all strategy views

### ISSUE THREAD

**Issue by mateonnelson** [TNRIS/iswp2017#209]
project triangles should map in all strategy supply views
the triangles don't show up in the usage type views yet

https://2017-staging.texasstatewaterplan.org/usagetype/manufacturing

**Comment by adambreznicky** [comment]
the triangles were left out of the usage type view because the query results are simply too large. this is the same reason there is no 'recommended projects' chart on the usage type views. the usage type views are statewide and there is simply too much data to efficiently display (in a chart-- let alone a map). it was an original decision between james and @sabrinaanderson i believe. there are comments in the code James has written which note why they were left out of that view. what do ya think? do you remember a discussion about that at all?

**Comment by mateonnelson** [comment]
Got it- thanks for reminder

.

On Jan 3, 2017, at 08:30, Brez <notifications@github.com<mailto:notifications@github.com>> wrote:


the triangles were left out of the usage type view because the query results are simply too large. this is the same reason there is no 'recommended projects' chart on the usage type views. the usage type views are statewide and there is simply too much data to efficiently display (in a chart-- let alone a map). it was an original decision between james and @sabrinaanderson<https://github.com/sabrinaanderson> i believe. there are comments in the code James has written which note why they were left out of that view. what do ya think? do you remember a discussion about that at all?

-

**Comment by SabrinaAnderson** [comment]
I don't remember the conversation with James, but you and I had spoken about it about a month ago and it made sense not to include them in the usage type view when we discussed it.

**Comment by adambreznicky** [comment]
right on. i'm going to close this issue for now. we can always reopen it if we decide to push through this in the future.
