### ISSUE TITLE
can't obtain names of sources in source view

### ISSUE THREAD

**Issue by mateonnelson** [TNRIS/iswp2017#212]
for example, one cannot discern the names of the reservoirs on the two maps that come up in the view:

https://2017-staging.texasstatewaterplan.org/source/810

**Comment by adambreznicky** [comment]
this is because this specific source is a system and although the system is made up of various other sources, we have no connection in the data between which individual sources are in which system. if you'd like a system source to display the names of the various sources which it comprises, we will need a separate table in the database with these source id relationships.... unless this relationship exists already in the database. 
@sabrinaanderson - do these source id relationships exist in any of the tables currently? or is it something that would have to be created?

**Comment by mateonnelson** [comment]
Sounds kinda complicated.
Leave for now.
Done.
m

**Comment by SabrinaAnderson** [comment]
We do have a table that links the SourceId which represents the system as whole to a SWId which is the primary key for each reservoir source that makes up the reservoir system. However, supply data is entered at the reservoir system level and the MapSourceId represents the reservoir system as a whole. Would you be able to label the individual sources in the source polygon if I created a view that includes MapSourceId, SWId, and Reservoir name? In cases where a reservoir is not part of a system, there would be one SWID per MapSourceId. If the source is a reservoir system, there will be one MapSourceId and one or more related SWIds in the new view.

**Comment by mateonnelson** [comment]
Ignore that issue.
Done.
m
