### ISSUE TITLE
UsageType Page Currently not Found

### ISSUE THREAD

**Issue by SabrinaAnderson** [TNRIS/iswp2017#222]
When I click on a usage type category in the staging application, it displays a message saying the page cannot be found and redirects to the home page.
![170120usagetypepagenotfoundmessage](https://cloud.githubusercontent.com/assets/23641348/22151005/b4b403cc-dee1-11e6-9570-db3badc5ac45.JPG)

**Comment by adambreznicky** [comment]
i am not getting this error. i have tried every usage type from the dropdown and they all seem to be working fine. i'm not getting any background console errors either...
can you show me the exact steps you're taking to get the error? what specifically you're clicking?

PS have you refreshed the app since my deployment yesterday? you'll want to refresh (press F5) a couple times to overwrite any cache.

**Comment by SabrinaAnderson** [comment]
I’ve refreshed a couple of times and the page is loading in Chrome, but in Internet Explorer, or Firefox I get the message ‘Page Not Found’.

**Comment by adambreznicky** [comment]
Usagetype url was acting as case sensitive.  Updating routing table to he insensitive in commit 4451d8
