### ISSUE TITLE
iswp: project data refresh

### ISSUE THREAD

**Issue by lebell** [TNRIS/iswp2017#227]
Hi,

We've made a couple modifications to project coordinates over the last few weeks.  Could you please perform a refresh on the data when you get a chance?  

Thank you!
Laura

**Comment by adambreznicky** [comment]
the updated data has been pulled and the application was redeployed utilizing it. considering the project view and numerous other changes which have been deployed since January, the app has been tagged as version 1.2 (latest release) with this deployment. 
please qc/verify the data changes and let me know if there are any issues. 
don't forget, you may need to clear your browser cache to see the changes (CTRL + F5).
completed via commit 49a19c56e00414265c7331a4c87da4adfd58bd34

**Comment by lebell** [comment]
Thank you!  I reviewed the changes and they look good.

Thanks,
Laura
