### ISSUE TITLE
Update the Water Management Strategies table on the WUG page

### ISSUE THREAD

**Issue by JasonKleinert** [TNRIS/iswp2017#234]
Update the Water Management Strategies table on the WUG page, https://2017.texasstatewaterplan.org/entity/<EntityId> to include hyperlinks to the WMS page for the individual strategies listed. If this cannot be done, then remove this table from the WUG page.
- __Function:__ When the user clicks a WMS name the associated WMS Id will be the parameter that is passed through to navigate to that specific strategy page. EX: https://2017.texasstatewaterplan.org/WMS/<WMSId> WMS name should act as the filter component in this table when there are multiple records.
- __Data:__ RWP.map.vwMapWMSWUGSupply

**Comment by JasonKleinert** [comment]
@lebell , would it be possible to add and populate the WmsProjectId field from the vw2017MapWMSProjectByEntityWUGSplit table to the vw2017MapWMSWugSupply table? I'm not sure how hard this is on your end, but this would make adding the links to the projects much easier.

**Comment by lebell** [comment]
Hi @JasonKleinert, we could left join WmsProjectId in to the vw2017MapWMSWugSupply table. However, some supplies are not associated with any project so these would be null in the WmsProjectId field, and in other situations there is a many to one relationship so duplicate WUG supply records would be created. Would this cause any problems for the application? 
As another option we could add WMSId to vw2017MapWMSProjectEntityRelationships which already includes WMSProjectId, EntityId, and MapSourceId if you think that would help with linking.

**Comment by lebell** [comment]
@JasonKleinert I also noticed that portions of the urls got lost in the transfer to waffle- i'm assuming because I used angle brackets. Not sure if that changes anything for you, but wanted to clarify with full documentation below: 

Update the Water Management Strategies table on the WUG page, https://2017.texasstatewaterplan.org/entity/[EntityId] to include hyperlinks to the WMS page for the individual strategies listed. If this cannot be done, then remove this table from the WUG page.
     o	Function: When the user clicks a WMS name the associated WMS Id will be the parameter that is passed through to navigate to that specific strategy page. EX: https://2017.texasstatewaterplan.org/WMS/[WMSId]. WMS name should act as the filter component in this table when there are multiple records.
     o	Data: RWP.map.vwMapWMSWUGSupply

**Comment by JasonKleinert** [comment]
@lebell The missing url endings have not been a problem, but thank you for clarifying for us. I have noticed that ProjectNames in vw2017MapWMSProjectByEntityWUGSplit do not always match WMSName in vw2017MapWMSWugSupply, (ex. CITY OF HOUSTON REUSE in vw2017MapWMSProjectByEntityWUGSplit  and COH REUSE in vw2017MapWMSWugSupply). I think these are describing the same project? This is making it difficult to just do a lookup across tables to create links, the links are driven by ProjectId. I think the left join may be ok, I would have to test it. When you say supplies do you mean WMStrategies? How would I know which projects to link to if there is a one to many relationship? I am under the impression that a WMSId is the same as a ProjectId, is this correct?

**Comment by JasonKleinert** [comment]
Ok @lebell , I think I may have gotten myself confused. Are these links supposed to be l;inking to the new WMS page that was requested? That would explain why I am having trouble understanding.

**Comment by SabrinaAnderson** [comment]
Laura is at a meeting right now, so I'll jump in to help clarify. WMSId and WMSProjectId are not the same. Think of a water management strategy (WMSId) as the WUGs plan to get water. In order to implement the WMS, one or more projects (WMSProjectIds) representing things like infrastructure and formal agreements associated with capital cost are required. A WUG (EntityId) may have more than one WMS associated with it and that WMS may require one or more projects. A WUG/WMS combination may not require a WMS project at all. An example of this is a conservation WMS where the utility alters the rates to impact water user behavior. No capital cost infrastructure is required in that scenario. A WUG may also not require a WMS if all of its projected demands are met and they have plenty of supplies to meet increasing demands. 

Hopefully that helps explain the data relationships a little better. It can be really confusing at first. Yes, you are correct. The WMS table on the WUG page will link to the new WMS page.

**Comment by JasonKleinert** [comment]
Ok, thank you for clarifying @SabrinaAnderson. I got a little confused here, but I think I'm starting to get it. Will there be a WMS Id added to the RWP.map.vwMapWMSWUGSupply table? I think that is all I will end up needing.

**Comment by JasonKleinert** [comment]
depends on completion of #229.

**Comment by SabrinaAnderson** [comment]
@JasonKleinert it should already be in the database if that view was refreshed. The view is called 'map.vw2017MapWMSWugSupply' and the WMSId is located about midway down the column name list.

**Comment by lebell** [comment]
Looks good, thank you! Please mark as done.
