### ISSUE TITLE
Add hyperlinks to the specific WMS Type page from the Strategy Supplies Breakdown section

### ISSUE THREAD

**Issue by JasonKleinert** [TNRIS/iswp2017#241]
#### Add hyperlinks to the specific WMS Type page from the Strategy Supplies Breakdown section with the pie chart on all pages showing the breakdown by strategy type.  
- __Function:__ Hyperlink text of WMS type data to have same functionality as other hyperlink text in raw data section. When the user clicks a WMS type this will be the parameter that is passed through to navigate to that specific water source page. EX: https://2017.texasstatewaterplan.org/wmstype/<wmstype>
- __Data:__ RWP.map.vwMapWMSWUGSupply

Pages that will need to be updated to include hyperlinks to water management strategy types:
 - Main Page - https://2017.texasstatewaterplan.org/statewide
 - Planning Region - https://2017.texasstatewaterplan.org/region/<RegionLetter>
 - County - https://2017.texasstatewaterplan.org/county/<CountyName>
 - Water User Group - https://2017.texasstatewaterplan.org/entity/<EntityId>
 - Usage Type - https://2017.texasstatewaterplan.org/usagetype/<UsageType>

![image](https://user-images.githubusercontent.com/5649664/30284623-0e75a926-96e1-11e7-8b97-6bb03b9aad0f.png)

**Comment by JasonKleinert** [comment]
depends on clompletion of #228

**Comment by lebell** [comment]
Comment also added to issue #228 - Whenever the application hyperlinks to the 'Drought Management' WMS type the link fails. We think this is caused by drought management not being associated with a project. The view to use that will allow the associated WMS to display without having a project is map.vw2017MapWMSWUGSupply. The view vw2017MapWMSProjectsByWMSType should only be used when displaying the list of projects related to a WMS type or displaying projects in the map view that are related to the WMS type.

**Comment by lebell** [comment]
Drought Management link works- thank you! Please update to done.
